apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-slow
spec:
  storageClassName: "local-host-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M