apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgAKC4ULXV2cAGlywe5jY7ZfFK7/KwK3z8bGnp8xyVFqNnfZIVCjvo/J1kNyW2HtAf5eBb3qZLGHpTde3aWnYFF7hhS9b+QtBhygqSpnkB75ZY43GSZGl44oqHEHmQTCYfnbCbCtQbnmtWyI9JRIimQTV6GoRTH1dxGtULOLJ4a5dI+dOYDMPlTefTPxLulQZglj3n6kLVShI7ErSjHzxoHCjpd6bXjiJ8/7i+Ucx+nk6pig5+Xh1YQdiDqOpFzYDiYIpRB0mLe30aRBhjIbnqzS9mHez0UxpPoi/zCbBlm7W2OYq6LxHb4jrdK2yDoQY8R3r9DV8tYx9c/fuFv6hGeWB5WGE1kRtFW0xtHjN6Io2nqTm0cH8TxCByxGnc6dt5c0kDNJAvcV1QRoIJPMlN80mvIU1OJLnYebQ6B8zNYPXOSOxkNQUgorLCLYKon9aVbl4AoI2+BzNZBIJQNDNcoKP6rwJTJhnvRjpofYq3QOsEWukIus88sJKhcRTi/z1vjUFA5M+OaD7uH1Zydh3Ey1v1B4km5woPoWFwr139r/S5qaD67wP3XREqNZn+LxRwWlcnJyxTH1838Im8aJmJGnhdK8KY5h1z+Bih0sSufxZJ7sUH086w/M8+2qfo7ghDeHL53Jh+7bE3gocOl8T11WZOZDUOvGMaFDSdrViPRFSvkLkh+1+Xt01l/lj4JNJAbf9we9w5zZNkOE0/+NMo+X
  template:
    metadata:
      name: harbor-admin-secret
      namespace: harbor