apiVersion: v2
name: project
description: Full project stack
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: project-postgres
    version: "1.0.0"
    repository: "file://../postgres"
    alias: postgres
    condition: postgres.enabled
  - name: project-redpanda
    version: "1.0.0"
    repository: "file://../redpanda"
    alias: redpanda
    condition: redpanda.enabled
  - name: project-service
    version: "1.0.0"
    repository: "file://../project-service"
    alias: project
    condition: project.enabled