apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: random-config
    literals:
      - JUST=some_env
      - AND=another_one

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: app
        labels:
          my-key: value