apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  labels:
    helm.sh/chart: project-service-1.0.0
    app.kubernetes.io/name: project-service
    app.kubernetes.io/instance: project
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: microservice
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 240
      containers:
      - name: migration
        image: inchanterx/faberge-project-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PG_USER
          value: "admin"
        - name: PG_HOST
          value: "postgres"
        - name: PG_PORT
          value: "5432"
        - name: PG_DB
          value: "project_db"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-auth
              key: POSTGRES_PASSWORD
        - name: DATABASE_DSN
          value: postgresql://$(PG_USER):$(POSTGRES_PASSWORD)@$(PG_HOST):$(PG_PORT)/$(PG_DB)
        command: ["uv", "run", "-m", "src.main", "migrate"]