apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- job.yaml
- ingress.yaml
- namespace.yaml
- service-pdb.yaml
- service-hpa.yaml
- postgres-sealed.yaml
- ./postgres
configMapGenerator:
- envs:
  - config.txt
  name: api-config
  options:
    annotations:
      argocd.argoproj.io/sync-wave: "-1"