apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: project-service-dev
spec:
  encryptedData:
    password: AgBCFmwlm9QN1c1qSpm5USNd6XvFp1/JDLvT+NsrX5tQZxToHCNA5mrjTh8H4PltBOoXYhfPlI73O7JccTW9hnCjs9Bck8hpRlEqAZBvqS3VFsjzdmfSwc3XCDhgYTrEgs6JMHJ3VpcWTZs6JIlcpUo5YSEOce1apKHKE4ED8h3qSJllnN2zDHHS6y3WDEeX9+yH4915qG8MI2DRUrycXZuG90XvQms7R1hLHUEPdPPOZYJ+DJAL1ZShVk0L4VSzkcpgzWKBcORH/pGq4S8+lEfnOsKxABHlDLPFOclPvU6/HhvH7NBWIkajB8a9D7G4ZcalXaJ4z9kiA6IM/QA8hDqKzihSTkTZfLAfyNQ94bQ/cKZvlJv7QB2kMbzlCFhmzAWq5OrNbsS6AQTJIbHZSNSIHHImcqJaqSU1+cF5vrQP+uCXi1aaNtzaVrEEAVL19BBhg2gTUc2IGBNp3YUlc7dCyQ9/1bs5AnG0FhJbJmxfVYrQxiTlFK9IAb6La7PXCJogXpeY3imltMvxHKo5MAkjDY5NDl9Z/Blv0d+drJlgAP7pjQFfL7oqzX5hDI7UEVzPXY0Ar1X3GYmwiLMqUqe/0F59WjL0I/i+HfTn6hNBxkB07x/FavKK6/u54ZigOFqbEEtPa7TsWGCO/j1Efz3vBQMn0hfM5G01YDvNgmV+7cE+tYbm7zAVqOIIvdJaXAPV+NpZl8Q2A4Aypv5T7rCnMGD8BdddlCQAOQ==
  template:
    metadata:
      name: postgres-auth
      namespace: project-service-dev
