apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAbASaLkL6+SmvC2eI5rIC8Pz0iCwlt07t0Mt8j7devW/2Syjg+ZGSgGFxuZXLdjqGG6UPq2C/6guXLTnufNT/IDeiyGjGUhdi6V/8EnXJhL6TTELfLqqj3xgqaA+z3fmMyiPjUgXCizFYtZLBI1H1uBh8ObBlmwqKOxPl7xP5QJlUyi6KQCI+LQ9T2/sfv1MIm57AtxoFkcrlnU5A6/17akSkbaAZoJmI1vxFKcl0EZ4PhkqDYRgLX/o14E3NNvx6tUqk+ty9RwITbOMei+THH/AVfJgKZoC2oeyCYO4zk2Uh1kRZBjSesaab1DxHVQzpKL8EsN2jnTaBLsFAdPgqXIoBDFY9fjyBrNnXTbW7TD53DfFzzepJKSb+rUjPLHf6yS7xz9En01pfOZln9ysB6KRXTjGArIaV1U74Tn2wfEVejCawxXkEe5eNN1muMxZO/VhEN3NTw0040rZMvHoYh6yoAKRvAIID/GuO6zNHSSu1DsJgUoF+7DE2ZiGP26Pvvdh0zUZsgB1v26cDkx65RWHT+ue8dWRtKA3BxtHMgn8Xpr9DE5RGtCaVPRirkZal3EeTU/StcvSrD7E3i+v/kKFZ9Ai88tGtjlqzoWnZKfDAFvWs4NT7luCtPu8DoZEOli1E3gJEUl8lTqnJi+UatToAb4sXM+TravNAn8GFQmUnw2fb1aX0R0MmFUjrPzbMu8eX3hTUA3ftewSrYutirkRdW3A==
  template:
    metadata:
      name: postgres-auth
      namespace: default
