apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pull-secret
  namespace: project-service-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAeB2DqNZjxc0I1E5L/zSTAmxH6pAG2IfWXn2B4XNg3rW05Oddh+DM/KwawpNFWT/xqkvlnT9kpXxbo8ODGPvbuT/Bb/tNIspWbeYPDkiE4DNQMlSKFI47wtkEZcj8ZgZiSlQhGnSUrp7v9dAPUnxjzh8sXdS6aHo/SyAb9WwKLQmuxU66/J5ZpgVjv3aE8qkuiMi2798NjppLOV128Xtkq4gH57VlsP8n0R8o5frBAYDeFLOyR2xaRlTQgspLs5VcfBD9yJr/NRzLS8k72dFdAN14ZWqb9xVcniF+afwEFxguhkgeybWwfyDxQ4dIKvdfkaVA0BAsZa1CrP6ySiQ1UZpx9c4j0LON/LobTHkke6bHXZwqOcH+2t6qedfPZ0dojdbw1F8wck2q8l+3Vg1kLEyr5yOJwIJ7OZ0Fi//8m0DZW8D7PoaWvgB3/6RIOLdgb1bgNp62XInf6kK+fI9zpS5ydrJK7dr8n0sOvuioUZt3ORRhwZYRVH0Qg+jio0udF/saDAGsu6nPP4RAgMH4UYyr03Jb1y5PVBkfVW7vamGxBEjDN2zwN3mRO7I4GyPVcJ9EjdR+GOR6C8D+hqiwaUin2IxatJboIEY4TlYfD6wRNopQqYuRcAut5CoeQsTRA9gh95n3X7EVAadLew9El7f/lFT9FoZc2hLlE5UXBB83HlrcNiA3EUkk5rsnvvg8AEgX8oFi5JPcxvglACoQRJ8llfWOhid8cKYzw6ix55wImo6MkcKkRPv9mmWZCmsxIchJdfy1e98VIcDHy6AnZg9UKNiupTZKKuaDGDpgZehA3AsrJJU2DLzdvWUI81Uyf0tVwxql4fp9XKZk39bJQvi6Z8qW+7UX/99LurC+zczmUCKrAwjDQ4jj+TUYq6UQ85lVZ+kvfipCiGuwowQQW7sHxhE9w+8fV4kZcB18AXCV4DFL6YMHsqImMeYegNHaIDNV2EDJd7u9ztImf4HsIcQ==
  template:
    metadata:
      name: harbor-pull-secret
      namespace: project-service-dev
    type: kubernetes.io/dockerconfigjson