apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pull-secret
  namespace: project-service-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBBtTNBB1HD543qxwp7JbIIpqh5VZuJjqBysI5HnrV/2GYyrnxbGGQBLTsmxLluRk3voqo299Uq2Zp3blJLzTpUMMFvqrsFTzwTyTd84dN/LepqPWk9vOi6EQKdg6MgpCHSE4SW4xrdX8GnX8IOJg2NY6LlJlS9O0yDiJC7dRihu6UyJzAs9KdY3ojJKaAUh40mlZABqMSuPE37y8VmOUrV4qyJ23L7UP1ktU+wGsRe0yRPUat7R482lVHeyP7F/JtPI9HJNyni/K0Q3bKeHfBd5V9jDWCgiK0rRyei1R+ogL9AQmWmh7C+/bryuB2nsFcg2oZ5gHHQTGAJnRs+O7WtWjIW9IoZ+fKKqqUXGAS/yYIul6Mdg3xMnUMJUsa1vKXkEOug/anW9blwWJPswzX8ZMOKbzsA0MdAREZrFMm1/On4+5l7quySYyif5TtvwfSq7poBHrFJzNmJWxGr8QMtFT/tFWbCS6VxVH/awg+od8O3t1iUkIStOGAJsg131xkFSvavJfMLio/IfSdTgLAz/zv0ctj/G/mf5L0nMrB1CnzuK4YgBhhdxP+vlfVAKNi0e7r2EOHqqmZ1nkA7r3dO9NI/YSSo2Q1Bcm7O+cuzR0DhLxhTZ8yMurPaLFiXTQE0hCWGpc8xMkVxJcwiBd+COjWEdFWsLO9ZKlC4sFwvoDd+Yv/YAwxTzROJCSyk7uaQRG8o57CssppMdi/T+rC1lMphFSo4MaX7qdBIpiZqCZef19mOAGj/ApNe5qnPD6r6V6oV4HmZHrsyK1LayE8prv8zIXNSX9+kPAqC9/zmVRSGJh0cPHffbT/gkvP/ueFnlHCtoSM3alJopTmavb4otdtLUt3xKuZ8sRPrN2hBG2nTEg==
  template:
    metadata:
      name: harbor-pull-secret
      namespace: project-service-dev
    type: kubernetes.io/dockerconfigjson
