apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pull-secret
  namespace: project-service-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCJo15WCtg3T4fHRhpjwzGISsk1BEBrhMaOnCZcrXX6CB434nM8me2hZvlVcU8gcXGmtqyfDPrT5cls8yZIca3gP2LEtWvReL4BuCzTCVQzqwW9V1Xz9pZ7M2uLdRlta/2EOpvOnRypiBbvHgXU83iDCgUH6KvufPlff+AonXHGNYVfmdzytfta8leMpqnr/wQLwpQurRUUB08c+2so8ZGJIW75cx432hWUwWi/uHeSIdTWgsVeABLxU2OpQmieTV/UhPL/kfn0yvkjpe7msgN1ghXTp4J1CWkp1OEa770cHAen48fTLX+6oo1QeS/4TFUWwFWZGCln8V9ZqygB32uxfz8BQeX+oQjhGnOH0f/QUITa2nZYWnLmXyfRA2tXt6rYcVRg05rJ8p9fmQo5n714mZ4qmFymUnZNfVc99oFoXysSgdfB2n73ZYPTarekwDi/ZdsUjDKHJlb5Knuo5HpoL6QhOuhY8ZCFeWmToO8oR6kfU8VhXDEcVG7QFnWhAmMyvZHJMSuAKrVMwMYd98ceSIXSvrI2fg5OBCwei4EGQfj6c7Fxh+QDBVMW7WL+e8gOa2D8YOEsgQMKehM87U/4KaiIP6vvtUB+vAOkXXBxaxgew/3v1uZqT0EpIjzkzjP+qoQ4rl3Q0mKbALIwA7tyhCaiMCf1izzMxZHcNuusWJwzrXTBrS68hq9Vld0LOwLx3Fi1c8ui5e0WNrVRp6/iLDfcRymY8dYVIjuhK7qt9iLu9bsVPmuFjgUKPpw8/BORMwaGOPx1EMR4lXleRrBwozaV4wHcrFShs5o+92CbjjrX2dHUTxYb0bjB5ly18ctPTHEqRBv0kkEACDZk9Y5z+k1eX92JyxVDZ806c6qVXBR/JB0dVT7EDXCHAfs8yw6qs8FSS07SliM0PwbpG74Fqhd5v3u0C3tEb4UwFFrKiddqzNlM7A0mBEh5FqqJDYNQRirmr9igCQtreT2cdbbYPw==
  template:
    metadata:
      name: harbor-pull-secret
      namespace: project-service-dev
    type: kubernetes.io/dockerconfigjson