apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-pull-access
  labels:
    service-environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
imagePullSecrets:
  - name: harbor-pull-secret