apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-gpg-keys-cm
data:
  D5E51FE406BF3E23: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQINBGp5hqgBEADhpw/8zWDAgYKoy3EhIunrc64Et4hwQ/5DzUKem3GT9dcOyUFT
    HougjAgh4kDNHAJKJ8qHo6dv08LQhuOmXpzjFauQSC6tAiUSh2WZPOIXe3eVJg2k
    JhNmACuklaXin12SDf6huRT+3j6KyUIGfOahvwZv5RHDkoPeq1M2K1yuGLc1T+Wp
    ywrpMFILED++acpz4FtZOALrI/wPE6+FbbN3zilRR7ZPVb9mR/k+YAl6uiDldDV8
    N3XRPg2TBu/xqQ4DLI3FehS4z1ASnyXXqp2JckgwQmH5K0Ew54oAk5inGo7wtjTv
    B3dfEkzLt2b/rCSeqV6CroTHVe78Treez8Lr0sa691rcMSQcA4pcG8wAp1EV1t+X
    t51xPk5HJHgS2NyMJnWBqw9nIdwqNz3437oGG2yfxYEX2bD7WbLm+se9c+9MEYZQ
    iORif37bognRyz9Edvo3TN2JV++xa+v4Pq0EP5TdRjde4+R6mTo116fm13v8v5ot
    Sby0W482oeYcp4txZ3PqwdCllF5avR1HgYjTwiQyzcByWERZBSzdVaKFyDbSxj2O
    Nki12dlqZk7Kt5eceZkkNDy2s1YE2Nk/Jy4Ra800Oj/TdKoVfsSfoFXYdm2SSSPg
    dJ/VjBG1o0XFHcFm/8gdH8ESaH0hKd0RGMg5KQcsW2Ulr7HzrpmP5hiOhwARAQAB
    tDlJbmNoYW50ZXJYIChMZWFkIHByb2plY3QgZGV2KSA8aW5jaGFudGVyeC53b3Jr
    QGdtYWlsLmNvbT6JAlEEEwEIADsWIQRETevwGWhML0a8uMLV5R/kBr8+IwUCanmG
    qAIbAwULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRDV5R/kBr8+I2x1EACT
    kTs1vtZiOUaxTb4tiPMCh8o8E134M4sqJscQBP7CJBmx65w70YXYXzx2Fck64sS9
    nc9NYCFSc69p2wb93z2JTbzti/mmURq2M2VNnYNE70NNYcEOI1jgMvyd65bbCOxD
    EfpLO0qDtnMv5LhPIPrkVdTtrh1joUBaMNnQbUfAlUna+rGMdYCUwdhGqkvcre3N
    +1iNxh2ZN/25vTKRs5QjRY7mslKz4kDir8bX/qI/CvtbqRjLa4tkJTGfu0fnOzz4
    qgMpaEjxfNXj+gPMs8Qgi3VrBK2axpf99iupNaJSSL4sOU6sbog9y8U5AkbOykcj
    SFyWQFtO/jafoALDgKDbHrRBex7DOu51TYKFEfMsY1/4vHUgJQvCYkQfjDP94D7m
    p/SDv3QrG4CWlC++MFRsQKJFwhAl25OENX6w28cEDPvK9jFSwNcu1tAe+C20yKNQ
    5LdmKvW6dlW7DWLXNGfnvTpXyOy96x4Q/3ZBJZYSnYUOK/dzf9Zc8StQ3Rds742e
    0A8fuDzdY+zU0UMzQvgzTyX8kc7oiVHxGp0E51MFtqLNrEOSvtPtC6YA5yBWgEuk
    0Kz67hDYe+NRFzTP+bcFj0nYJ97pu2/NcXtaYAobKFVkhtP0yQh6P+cswDrpDBCY
    MhgFvGQ6XBV032ZFp1xZaXBjDuv80qSJeY9RFa4CvrkCDQRqeYaoARAA8eF+VkN4
    ziFOMbI5gMNsIC5gnHGpfGbmJX7mBi4XqIRnp2Q7DYYa2nXlCSu0iD6Qmms4y9+G
    P1Elq33HFUMuzIaKpLJQKgT6yW7XKWZh/Z3TlltPc7KqApswEuGJGQWHAhVGdHN5
    DFkcdMaYsY2j1TzGwfRwFT0TqWfn97KxJEcQ8TPymcAdGRgZijZSXvEejckaP+Ys
    E7p9oGLQkrPsOtUHRz+WI6unSpTPHKyL6gAwj/jot029acS9clKD1/r1fEsx6M1x
    vhMFX7A3t30N7aotU1fEM09fcA5vmrEEwQH8KLLjXbeiqJ0Ah+khAVA6+pfuRm74
    yqGFY2qEgwCAq8QI9H4wrSqkMJOX8KZr4jDc/ZbzNp0+lZ7lidxf0ZvCx1mN951d
    Q2S3ujWt3+BNwWquiKuAKDAkTGM2B5PcbxaAAm3Xs/GjZVsYhxeKqL8Xl9nOaR58
    nzNLKnCffUApK4wkLl5XL2X7m+B7/jvSXwUs9OYJcawVqWbejpmU8kQJl3dQMKqM
    p+ZunRiwkSvdPAnqarIu8yGKNUpgVTVTjwhtZObdpYEmL38C6i0axpN6/s7Mwu6q
    9M4L9pCYZ32uRcTlqg2MUmVjiFhkU/BRmb5qUcSnaZUvsqmPF7fWuBkY8DCBd9Qt
    zdpFZIo6uHclP9KG3+7Qcabw7FebIO+wlecAEQEAAYkCNgQYAQgAIBYhBERN6/AZ
    aEwvRry4wtXlH+QGvz4jBQJqeYaoAhsMAAoJENXlH+QGvz4jdFwP/3kyQHIXGWHR
    2MFLeSzUhzpg19lnGGfa/424hPMPXX55efSv4gftBv0s/rJXBmQ4y5we5JjWfPX4
    NhIp0Dw8VEW0EbsPivBweJuWSQCv6B67d9dXIDglA7EKM0/Lrq5AIgFnNeMpjsu2
    P+MmXPKY+idrJ2iCCxOVSj2uDSZrdnkwpuzwBDLkxKmE6X2jjXtW97DP6yt1U3Qe
    LNvRqEPGToxWk+iJ/F7x8Q0ApDUmybVV5Jaay85acg+9uP8lDKIHsR8HsuADlzLu
    kmOYsjfKV30epJjjL9H+CPLBllnmeATf24dEotgASLn8EqjZYz20yM4AvzEq3drJ
    Ept+zkGb1LML0oFticlClo9xTWTI/GtS2F9HdayZi7t7fMd0OqOQrorrUNG7LPs0
    8531OMdRq8ZQoGqqgmKzgNEuHYK2m/job78bVqvrAJQi7HZXdB/37qhtGdo/bOU6
    aM6+atF7NnvPwCu4cdl+lG82oSiUzLvSyP4xEapeRanlRXFZJOybxSfbltonLa/d
    sqNGvyx67l0apHU9Fp7F+jSvAOOMuPI8qv+9ddcCq7glDTT4z5uCaTFvuC7m+P7N
    r/FQoKheFt/3RxwRJGiGHnJQx5EW2M3lwWGlKL4vXbfbj2Rk42RBPMvP95AswSEx
    bdmLKNRzhOP6o67GDihxTzQh8opYLWIR
    =Uv6W
    -----END PGP PUBLIC KEY BLOCK-----
  B5690EEEBB952194: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQINBGWmxXYBEACyN+4viFQM6QQoKr0A2W0rGdMobTJwOZso2QPpewbyBsuL3rNW
    5OmHrWwXAhPKNqUIyOzdq8MoSxoTTuqLksoahixEL/X2nyhOBxR9GkYz/oI9R3nY
    cLRaFQoSJoVfOt61opkLUzbWAehpbgT8EKln8JsENq0+0nDlWQi0h2Q9oGmqlgVz
    skwmVZ8Leyv4Mg7hN6swyZ7moZfkkpD5+U7Z2XVurCzkSSfg4zb2lMRLJos2eCAc
    749ECsX0t7OBftF+YqgjIXixXsm2RrUqvU47OkOtZeAhvAYenbC3pr9Fha5NxoBU
    Ea+11MK9W6OcRhwvxVCUrMUR6FTSZyC//VpXTTtrRlOqpU5wGMbP3zpn9geqOXCl
    8rF7+1gAPG/o+QFQTBsVEruwi4JWogiQuQyOwAIlFe/7dvaxWZGpv/yW2+L3guL7
    xaHKFVGsayhlitQQ5Xa+P1iSgKSXDyReCbWotfqAempPySI25LHh3ScXI6NgdHSr
    SBaFojwAfgxbPTEQ6adIsKHCQofrnLrNa3UOeGDGiOOK0aYV3jiEDGAouatkNf2q
    85Eosj1f9laCqAH3YLJD7dcSne1iChK5qRTByMvIyeSD0NbNnVMFOGpXySyWtKb2
    ldpu8AWBQJsJs9FmYBcWAGBA2pp+IxaCn6rBIHIsUVFRN8OVZKsEsBkWywARAQAB
    tBtHaXRIdWIgPG5vcmVwbHlAZ2l0aHViLmNvbT6JAk4EEwEKADgWIQSWhHmhr/kn
    430aVmu1aQ7uu5UhlAUCZabFdgIbAwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAK
    CRC1aQ7uu5UhlIMuEAClvVwC+Neoiq0AdixJZsagKHpx1QrMJWrtMRi4eXVTTaeX
    +P1unhC/AmSO4Xxd3uRoejHvfWh4F0gitUJ8XKgiejnmuGcq7Dbt5OoO1JuXGlW2
    BQ+MiGoYVw2B0sOhWDNrIBWOO/WL4LykcGnAtrRXwoS0Wx4MCydztXQY5lcnCWaW
    8rvu7WmduoOikH4HI97rqN5896dc4iBKSx8LZf+46DRCCD/5SfACplBz4hs5zen8
    TL8zd+zxjFrXbzota0jSDEGK9WGO4z55S2xScC6zv6v3Bj1OR8Bs5aodGtmamHZ7
    sE9w0RJoCfNx+9cR/rE82SrOaBpVU7urLe4lg7zaaNhqDdNV8ymuXGmIJarDgrme
    iB5bHS+dLFzLUkTgot4RFlPa9bFiJuJN6Tc9tMu5RJQ9l/zKmxDHIKWsAle5R65u
    zEq04LugTQBdEorGxfQCsF2ga9ncKTDMiAThWTvZpOP3NJ/athZRmOBpG4B9iR6r
    pRU8F/+MokG4fIMwnvtOhWQFiEzdTkJ7U5JAkPtTAmT3/mznwtPEU7DrFWSGAdqg
    IMOlxNCBeGvjwLR0qGH7cB9qHDGNoDLkjaUFpu5tPv4/ivkQaHlHJxjT0ILM6jet
    CAzKpKh48rm65tmrJX6KVpj0r2kKMscFf7s7XaPlCNCFds/YA+0puPbzJKWKfA==
    =NRlX
    -----END PGP PUBLIC KEY BLOCK-----
