apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-gpg-keys-cm
data:
  D5E51FE406BF3E23: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQINBGp5hqgBEADhpw/8zWDAgYKoy3EhIunrc64Et4hwQ/5DzUKem3GT9dcOyUFT
    HougjAgh4kDNHAJKJ8qHo6dv08LQhuOmXpzjFauQSC6tAiUSh2WZPOIXe3eVJg2k
    JhNmACuklaXin12SDf6huRT+3j6KyUIGfOahvwZv5RHDkoPeq1M2K1yuGLc1T+Wp
    ywrpMFILED++acpz4FtZOALrI/wPE6+FbbN3zilRR7ZPVb9mR/k+YAl6uiDldDV8
    N3XRPg2TBu/xqQ4DLI3FehS4z1ASnyXXqp2JckgwQmH5K0Ew54oAk5inGo7wtjTv
    B3dfEkzLt2b/rCSeqV6CroTHVe78Treez8Lr0sa691rcMSQcA4pcG8wAp1EV1t+X
    t51xPk5HJHgS2NyMJnWBqw9nIdwqNz3437oGG2yfxYEX2bD7WbLm+se9c+9MEYZQ
    iORif37bognRyz9Edvo3TN2JV++xa+v4Pq0EP5TdRjde4+R6mTo116fm13v8v5ot
    Sby0W482oeYcp4txZ3PqwdCllF5avR1HgYjTwiQyzcByWERZBSzdVaKFyDbSxj2O
    Nki12dlqZk7Kt5eceZkkNDy2s1YE2Nk/Jy4Ra800Oj/TdKoVfsSfoFXYdm2SSSPg
    dJ/VjBG1o0XFHcFm/8gdH8ESaH0hKd0RGMg5KQcsW2Ulr7HzrpmP5hiOhwARAQAB
    tDlJbmNoYW50ZXJYIChMZWFkIHByb2plY3QgZGV2KSA8aW5jaGFudGVyeC53b3Jr
    QGdtYWlsLmNvbT6JAlEEEwEIADsWIQRETevwGWhML0a8uMLV5R/kBr8+IwUCanmG
    qAIbAwULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRDV5R/kBr8+I2x1EACT
    kTs1vtZiOUaxTb4tiPMCh8o8E134M4sqJscQBP7CJBmx65w70YXYXzx2Fck64sS9
    nc9NYCFSc69p2wb93z2JTbzti/mmURq2M2VNnYNE70NNYcEOI1jgMvyd65bbCOxD
    EfpLO0qDtnMv5LhPIPrkVdTtrh1joUBaMNnQbUfAlUna+rGMdYCUwdhGqkvcre3N
    +1iNxh2ZN/25vTKRs5QjRY7mslKz4kDir8bX/qI/CvtbqRjLa4tkJTGfu0fnOzz4
    qgMpaEjxfNXj+gPMs8Qgi3VrBK2axpf99iupNaJSSL4sOU6sbog9y8U5AkbOykcj
    SFyWQFtO/jafoALDgKDbHrRBex7DOu51TYKFEfMsY1/4vHUgJQvCYkQfjDP94D7m
    p/SDv3QrG4CWlC++MFRsQKJFwhAl25OENX6w28cEDPvK9jFSwNcu1tAe+C20yKNQ
    5LdmKvW6dlW7DWLXNGfnvTpXyOy96x4Q/3ZBJZYSnYUOK/dzf9Zc8StQ3Rds742e
    0A8fuDzdY+zU0UMzQvgzTyX8kc7oiVHxGp0E51MFtqLNrEOSvtPtC6YA5yBWgEuk
    0Kz67hDYe+NRFzTP+bcFj0nYJ97pu2/NcXtaYAobKFVkhtP0yQh6P+cswDrpDBCY
    MhgFvGQ6XBV032ZFp1xZaXBjDuv80qSJeY9RFa4CvrkCDQRqeYaoARAA8eF+VkN4
    ziFOMbI5gMNsIC5gnHGpfGbmJX7mBi4XqIRnp2Q7DYYa2nXlCSu0iD6Qmms4y9+G
    P1Elq33HFUMuzIaKpLJQKgT6yW7XKWZh/Z3TlltPc7KqApswEuGJGQWHAhVGdHN5
    DFkcdMaYsY2j1TzGwfRwFT0TqWfn97KxJEcQ8TPymcAdGRgZijZSXvEejckaP+Ys
    E7p9oGLQkrPsOtUHRz+WI6unSpTPHKyL6gAwj/jot029acS9clKD1/r1fEsx6M1x
    vhMFX7A3t30N7aotU1fEM09fcA5vmrEEwQH8KLLjXbeiqJ0Ah+khAVA6+pfuRm74
    yqGFY2qEgwCAq8QI9H4wrSqkMJOX8KZr4jDc/ZbzNp0+lZ7lidxf0ZvCx1mN951d
    Q2S3ujWt3+BNwWquiKuAKDAkTGM2B5PcbxaAAm3Xs/GjZVsYhxeKqL8Xl9nOaR58
    nzNLKnCffUApK4wkLl5XL2X7m+B7/jvSXwUs9OYJcawVqWbejpmU8kQJl3dQMKqM
    p+ZunRiwkSvdPAnqarIu8yGKNUpgVTVTjwhtZObdpYEmL38C6i0axpN6/s7Mwu6q
    9M4L9pCYZ32uRcTlqg2MUmVjiFhkU/BRmb5qUcSnaZUvsqmPF7fWuBkY8DCBd9Qt
    zdpFZIo6uHclP9KG3+7Qcabw7FebIO+wlecAEQEAAYkCNgQYAQgAIBYhBERN6/AZ
    aEwvRry4wtXlH+QGvz4jBQJqeYaoAhsMAAoJENXlH+QGvz4jdFwP/3kyQHIXGWHR
    2MFLeSzUhzpg19lnGGfa/424hPMPXX55efSv4gftBv0s/rJXBmQ4y5we5JjWfPX4
    NhIp0Dw8VEW0EbsPivBweJuWSQCv6B67d9dXIDglA7EKM0/Lrq5AIgFnNeMpjsu2
    P+MmXPKY+idrJ2iCCxOVSj2uDSZrdnkwpuzwBDLkxKmE6X2jjXtW97DP6yt1U3Qe
    LNvRqEPGToxWk+iJ/F7x8Q0ApDUmybVV5Jaay85acg+9uP8lDKIHsR8HsuADlzLu
    kmOYsjfKV30epJjjL9H+CPLBllnmeATf24dEotgASLn8EqjZYz20yM4AvzEq3drJ
    Ept+zkGb1LML0oFticlClo9xTWTI/GtS2F9HdayZi7t7fMd0OqOQrorrUNG7LPs0
    8531OMdRq8ZQoGqqgmKzgNEuHYK2m/job78bVqvrAJQi7HZXdB/37qhtGdo/bOU6
    aM6+atF7NnvPwCu4cdl+lG82oSiUzLvSyP4xEapeRanlRXFZJOybxSfbltonLa/d
    sqNGvyx67l0apHU9Fp7F+jSvAOOMuPI8qv+9ddcCq7glDTT4z5uCaTFvuC7m+P7N
    r/FQoKheFt/3RxwRJGiGHnJQx5EW2M3lwWGlKL4vXbfbj2Rk42RBPMvP95AswSEx
    bdmLKNRzhOP6o67GDihxTzQh8opYLWIR
    =Uv6W
    -----END PGP PUBLIC KEY BLOCK-----
  566BB5690EEEBB95: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    xsBNBFmUaEEBCACzXTDt6ZnyaVtueZASBzgnAmK13q9Urgch+sKYeIhdymjuMQta
    x15OklctmrZtqre5kwPUosG3/B2/ikuPYElcHgGPL4uL5Em6S5C/oozfkYzhwRrT
    SQzvYjsE4I34To4UdE9KA97wrQjGoz2Bx72WDLyWwctD3DKQtYeHXswXXtXwKfjQ
    7Fy4+Bf5IPh76dA8NJ6UtjjLIDlKqdxLW4atHe6xWFaJ+XdLUtsAroZcXBeWDCPa
    buXCDscJcLJRKZVc62gOZXXtPfoHqvUPp3nuLA4YjH9bphbrMWMf810Wxz9JTd3v
    yWgGqNY0zbBqeZoGv+TuExlRHT8ASGFS9SVDABEBAAHNNUdpdEh1YiAod2ViLWZs
    b3cgY29tbWl0IHNpZ25pbmcpIDxub3JlcGx5QGdpdGh1Yi5jb20+wsBoBBMBCAAc
    BQJZlGhBCRBK7hj4Ov3rIwIbAwUJDBJ3/wIZAQAA0O4IAJd0k8M+urETyMvTqNTj
    /U6nbqyOdKE4V93uUj5G7sNTfno7wod/Qjj6Zv5KodvA93HmEdQqsmVq5YJ5KGiw
    cmGCpd/GqJRPaYSY0hSUSBqYHiHLusCJkPBpQTBhcEMtfVCB2J6fVeoX2DV0K1xf
    CGblrSVB0viAxUMnmL5C55RuvbYZsTu8szXhkvIR96CtWbJ8QGaEf1/KSpWz8ept
    Y/omf3UPfvdOjnsxc8jVEqPNaR9xC6Q6t53rBa/XgMY6IYyesnyYnc5O6JuexUFa
    VjykRFtAiYfDaMARpXOmgMm0lhoBRKb/uMUaN3CSYTmE4pZweJcUi7eWgmoQljX2
    ut6ZAg0EZabFdgEQALI37i+IVAzpBCgqvQDZbSsZ0yhtMnA5myjZA+l7BvIGy4ve
    s1bk6YetbBcCE8o2pQjI7N2rwyhLGhNO6ouSyhqGLEQv9fafKE4HFH0aRjP+gj1H
    edhwtFoVChImhV863rWimQtTNtYB6GluBPwQqWfwmwQ2rT7ScOVZCLSHZD2gaaqW
    BXOyTCZVnwt7K/gyDuE3qzDJnuahl+SSkPn5TtnZdW6sLORJJ+DjNvaUxEsmizZ4
    IBzvj0QKxfS3s4F+0X5iqCMheLFeybZGtSq9Tjs6Q61l4CG8Bh6dsLemv0WFrk3G
    gFQRr7XUwr1bo5xGHC/FUJSsxRHoVNJnIL/9WldNO2tGU6qlTnAYxs/fOmf2B6o5
    cKXysXv7WAA8b+j5AVBMGxUSu7CLglaiCJC5DI7AAiUV7/t29rFZkam//Jbb4veC
    4vvFocoVUaxrKGWK1BDldr4/WJKApJcPJF4Jtai1+oB6ak/JIjbkseHdJxcjo2B0
    dKtIFoWiPAB+DFs9MRDpp0iwocJCh+ucus1rdQ54YMaI44rRphXeOIQMYCi5q2Q1
    /arzkSiyPV/2VoKoAfdgskPt1xKd7WIKErmpFMHIy8jJ5IPQ1s2dUwU4alfJLJa0
    pvaV2m7wBYFAmwmz0WZgFxYAYEDamn4jFoKfqsEgcixRUVE3w5VkqwSwGRbLABEB
    AAG0G0dpdEh1YiA8bm9yZXBseUBnaXRodWIuY29tPokCTgQTAQoAOBYhBJaEeaGv
    +SfjfRpWa7VpDu67lSGUBQJlpsV2AhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheA
    AAoJELVpDu67lSGUgy4QAKW9XAL416iKrQB2LElmxqAoenHVCswlau0xGLh5dVNN
    p5f4/W6eEL8CZI7hfF3e5Gh6Me99aHgXSCK1QnxcqCJ6Oea4ZyrsNu3k6g7Um5ca
    VbYFD4yIahhXDYHSw6FYM2sgFY479YvgvKRwacC2tFfChLRbHgwLJ3O1dBjmVycJ
    Zpbyu+7taZ26g6KQfgcj3uuo3nz3p1ziIEpLHwtl/7joNEIIP/lJ8AKmUHPiGznN
    6fxMvzN37PGMWtdvOi1rSNIMQYr1YY7jPnlLbFJwLrO/q/cGPU5HwGzlqh0a2ZqY
    dnuwT3DREmgJ83H71xH+sTzZKs5oGlVTu6st7iWDvNpo2GoN01XzKa5caYglqsOC
    uZ6IHlsdL50sXMtSROCi3hEWU9r1sWIm4k3pNz20y7lElD2X/MqbEMcgpawCV7lH
    rm7MSrTgu6BNAF0SisbF9AKwXaBr2dwpMMyIBOFZO9mk4/c0n9q2FlGY4GkbgH2J
    HqulFTwX/4yiQbh8gzCe+06FZAWITN1OQntTkkCQ+1MCZPf+bOfC08RTsOsVZIYB
    2qAgw6XE0IF4a+PAtHSoYftwH2ocMY2gMuSNpQWm7m0+/j+K+RBoeUcnGNPQgszq
    N60IDMqkqHjyubrm2aslfopWmPSvaQoyxwV/uztdo+UI0IV2z9gD7Sm49vMkpYp8
    =uMz0
    -----END PGP PUBLIC KEY BLOCK-----