apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |-
    p, role:deployer, applications, sync, */*, allow
    p, role:deployer, applications, get, */*, allow
    p, role:deployer, applications, action/*, */*, allow
    g, myuser, role:deployer
