apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: redpanda
    count: 1
namespace: event-broker-prod
labels:
  - pairs:
      enviroment: prod
patches:
  - path: patches/statefulset.yaml
    target:
      kind: Statefulset
      name: redpanda
  - patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 1
    target:
      name: postgres
      kind: PodDisruptionBudget