apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: infrastructure-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  encryptedData:
    api-token: AgA48/r+7QVVPwPDZMJ5FXk/7u6oXvbc6YJsq/maIscEjVG4sj7aWF0RKlQN2vWfRWARUtshnyLuLrHzv3aS6aDzWFRub44RwgHJywVjC4o/tIbQ/c8hohYR1n0Oyp4D4+nADvQjttMGeV+b2qXZS559wms0p4mcCjHC0/2xoVnzXbJYgMIcj4Z/6YRnn+hq4bgCxpXboVsf9lbpJGydA/+sfsex5ng1rga8JZCnwgnnQyhB4G8Y7u1Z2fxVy+L9Hl09rDAr4hUYK0sK4xWnstSiO/ya6fnatSkoTNkUdfXV3VvaPVmjvEjY84u19XtyMW/jpSSRjljlcznmoDJ7lgYjvtyQdyHjbQNtFCPlkcSZ08XTcSnily6tkND8Qr1UxFLaqglEHBqGMsk7j0nvaS0QXBn6kApoJRjuaY31Rcbq3UDGrBTlJmletk/iTWOhiTL7dx5+JmN0NoGX6HTS37MU2OYADlTzKWEWwWI6hxPTS8Bxi50/Tcv7tmj1X1Zyiu9WKSVamth+woxbP/3E9xUIByNFtj4WnYIZ5XEyg20dSoBpPSWET1ARSjyDQoDaEW2wYEhkZlI9pL87cFWfOYXpzFFD7Vc//zVaAGI5fOf4kLXI9xPRbZcxVw9Ub3gCGoJxJ56SDUFKwDZwoRhT7MdvgaeKfWLiYforbvfEyH+F6NiXBsf4U2BmCOQVqVRRUg1Wv9bw0C90/xmMlAHB3l97mQeCV8kskabrh6vTt5DJ0ndI1lvu9It1A7wh0JL4TY8qX+mXDw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: infrastructure-dev
