apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - prod-cert.yaml
  - prod-issuer.yaml
  - cloudflare-token-secret.yaml
  - ca-certificate.yaml
  - ca-issuer.yaml
  - project-service-cert.yaml
  - project-service-issuer.yaml