apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project.config" . }}
data:
  LOG_LEVEL: {{ .Values.parameters.log_level | quote}}
  KAFKA_TOPIC_ANSWERS: {{ .Values.parameters.kafka_topic_answers | quote }}
  KAFKA_TOPIC_COMMENTS: {{ .Values.parameters.kafka_topic_comments | quote }}
  KAFKA_TOPIC_PROFILE: {{ .Values.parameters.kafka_topic_profile | quote }}
  KAFKA_TOPIC_EVENTS: {{ .Values.parameters.kafka_topic_events | quote }}
  KAFKA_GROUP_ID: {{ .Values.parameters.kafka_group_id | quote }}
  KAFKA_BOOTSTRAP: {{ printf "%s:%v" (.Values.kafka.host | default (include "project.kafka_host" .)) ( include "project.kafka_port" . | int) | quote }}
  HTTP_HOST: "0.0.0.0"
  HTTP_PORT: {{ .Values.port | quote }}
  DATABASE_MIN_CONNECTIONS: {{ .Values.postgres.minConnections | quote }}
  DATABASE_MAX_CONNECTIONS: {{ .Values.postgres.maxConnections | quote }}
