apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - project-service-limitrange.yaml
  - priority-low.yaml
  - priority-middle.yaml
  - priority-high.yaml
  - priority-critical.yaml
  - project-service-quota.yaml
namespace: infrastructure
patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: project-service
    target:
      kind: LimitRange
      name: project-service
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: project-service
    target:
      kind: ResourceQuota
      name: project-service