apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: middle
value: 100
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Middle priority class for average pods"