apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-service
  namespace: project-service
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "3Gi"
    requests.storage: "10Gi"
    limits.cpu: "3"
    limits.memory: "3Gi"