apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: project
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgres