apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - headless.yaml
  - statefulset.yaml
configMapGenerator:
  - name: postgres-config
    envs:
      - config.txt
generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"