apiVersion: v1
kind: Service
metadata:
  name: redpanda-headless
spec:
  selector:
    app.kubernetes.io/name: redpanda-pod
    app.kubernetes.io/instance: test
  clusterIP: None
  ports:
    - port: 9092
      targetPort: kafka-api