apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Project for services infrastructure

  signatureKeys:
    - keyID: D5E51FE406BF3E23
    - keyID: B5690EEEBB952194

  sourceRepos:
    - https://github.com/InchanterX/kuber_education

  destinations:
    - server: https://kubernetes.default.svc
      namespace: 'project-service-*'
    - server: https://kubernetes.default.svc
      namespace: 'event-broker-*'

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  namespaceResourceBlacklist:
    - group: ''
      kind: LimitRange
    - group: ''
      kind: ResourceQuota
    - group: 'networking.k8s.io'
      kind: NetworkPolicy

  orphanedResources:
    warn: true

  roles:
    - name: deployer
      policies:
        # формат subject: proj:<проект>:<роль>
        - p, proj:team-backend:deployer, applications, sync, team-backend/*, allow
        - p, proj:team-backend:deployer, applications, get,  team-backend/*, allow