apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: infra-project

  source:
    repoURL: https://helm.goharbor.io
    targetRevision: 1.19.2
    chart: harbor
    helm:
      values: |
        expose:
          type: clusterIP
          tls:
            enabled: false

        externalURL: https://registry.faberge-eggs.ru

        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              storageClass: local-path-retain
              size: 50Gi
            database:
              storageClass: local-path-retain
              size: 5Gi
            redis:
              storageClass: local-path
              size: 1Gi
            trivy:
              storageClass: local-path
              size: 5Gi
            jobservice:
              jobLog:
                storageClass: local-path
                size: 1Gi
        database:
          type: internal
        redis:
          type: internal
        trivy:
          enabled: true
        harborAdminPassword: temp

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  info:
    - name: 'Harbor:'
      value: 'https://helm.goharbor.io'

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m