apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: infra-project

  sources:
    - repoURL: registry.faberge-eggs.ru/mirror
      chart: vault
      targetRevision: 0.34.1
      helm:
        values: |
          global:
            tlsDisable: true
          server:
            ha:
              enabled: true
              replicas: 1
              raft:
                enabled: true
                setNodeId: true
                config: |
                  ui = true
                  listener "tcp" {
                    address       = "[::]:8200"
                    cluster_address = "[::]:8201"
                    tls_disable   = 1
                  }
                  storage "raft" {
                    path = "/vault/data"
                  }
                  seal "transit" {
                    address   = "http://10.0.0.1:8200"
                    key_name  = "autounseal-main"
                    mount_path = "transit/"
                  }
                  service_registration "kubernetes" {}
                  disable_mlock = true
            extraEnvironmentVars: {}
            extraSecretEnvironmentVars:
              - envName: VAULT_SEAL_TRANSIT_TOKEN
                secretName: vault-transit-token
                secretKey: token
            dataStorage:
              enabled: true
              size: 5Gi
              storageClass: local-path-retain
              mountPath: /vault/data
          ui:
            enabled: true
    - repoURL: https://github.com/InchanterX/kuber_education.git
      targetRevision: main
      path: kustomization/vault-router/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'

  revisionHistoryLimit: 10

  info:
    - name: 'Vault'
      value: 'https://registry.faberge-eggs.ru/mirror'

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m