apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - job.yaml
  - ingress.yaml
  - namespace.yaml
  - ./postgres
sortOptions:
  order: legacy
configMapGenerator:
  - name: api-config
    envs:
      - config.txt
secretGenerator:
  - name: postgres-auth
    envs:
      - secret.txt
namespace: project-service
replicas:
  - name: app
    count: 3